export default [
    {
        "_id": "627e7f5f573fe36115400601",
        "title": "Sri Lanka crisis: How war heroes became villains",
        "desc": "<h2><strong>s?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many years.</p><p>India's rivalry with Pakistan, and increasingly with China, means Russia has remained a key partner for Delhi, even after the collapse of the Soviet Union in the 1990s.</p><p>&nbsp;</p><p><strong>ndia's long-standing ties to Russia have come under the spotlight - especially in the defence sector - following the invasion of Ukraine.</strong></p><p>Finance Minister Nirmala Sitharaman said during a visit to the US in April that India would like to be a 'good friend' to Western countries.</p><p>But she added that India didn't want to be weakened, and needed to ensure its security - taken to mean its long-standing reliance on Russian military equipment - would continue.</p><h2><strong>How dependent is India on Russian arms?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many y</p>",
        "category": "Interview",
        "url": "Sri-Lanka-crisis",
        "banner": "banner-1652457311713-920593162.jpeg",
        "thumbnail": "thumbnail-1652457311683-276650335.jpeg",
        "slug": "",
        "createdAtTimestamp": "1652402567931",
        "createdAtDateTime": "13/5/2565 07:42",
        "__v": 0,
        "createdBy": {
            "_id": "62771c4ee352657da55dcdfe",
            "username": "tester",
            "__v": 0
        }
    },
    {
        "_id": "627e800d573fe36115400610",
        "title": "Denisova did not provide any evidence to support her claims and the BBC has not been able to verify them.",
        "desc": "<h2><strong>s?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many years.</p><p>India's rivalry with Pakistan, and increasingly with China, means Russia has remained a key partner for Delhi, even after the collapse of the Soviet Union in the 1990s.</p><p>&nbsp;</p><p><strong>ndia's long-standing ties to Russia have come under the spotlight - especially in the defence sector - following the invasion of Ukraine.</strong></p><p>Finance Minister Nirmala Sitharaman said during a visit to the US in April that India would like to be a 'good friend' to Western countries.</p><p>But she added that India didn't want to be weakened, and needed to ensure its security - taken to mean its long-standing reliance on Russian military equipment - would continue.</p><h2><strong>How dependent is India on Russian arms?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many y</p>",
        "category": "Interview",
        "url": "Denisova-did-not-provide-any",
        "banner": "banner-1652457485010-223692916.jpeg",
        "thumbnail": "thumbnail-1652457485000-405880991.jpeg",
        "slug": "",
        "createdAtTimestamp": "1652402567931",
        "createdAtDateTime": "13/5/2565 07:42",
        "__v": 0
    },
    {
        "_id": "627e8136573fe36115400628",
        "title": "Russia and Finland share a 1,300km (810-mile) border. Finland has been non-aligned since World War Two and has always sought not to antagonise its eastern neighbour.",
        "desc": "<h2><strong>s?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many years.</p><p>India's rivalry with Pakistan, and increasingly with China, means Russia has remained a key partner for Delhi, even after the collapse of the Soviet Union in the 1990s.</p><p>&nbsp;</p><p><strong>ndia's long-standing ties to Russia have come under the spotlight - especially in the defence sector - following the invasion of Ukraine.</strong></p><p>Finance Minister Nirmala Sitharaman said during a visit to the US in April that India would like to be a 'good friend' to Western countries.</p><p>But she added that India didn't want to be weakened, and needed to ensure its security - taken to mean its long-standing reliance on Russian military equipment - would continue.</p><h2><strong>How dependent is India on Russian arms?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many y</p>",
        "category": "Interview",
        "url": "land-share-a-130",
        "banner": "banner-1652457782875-501665071.jpeg",
        "thumbnail": "thumbnail-1652457782765-30136235.jpeg",
        "slug": "",
        "createdAtTimestamp": "1652402567931",
        "createdAtDateTime": "13/5/2565 07:42",
        "__v": 0
    },
    {
        "_id": "627e7fe6573fe3611540060c",
        "title": "Volodymyr Zelensky is ready to speak directly with Russian President Vladimir Putin, but 'only without any intermediaries', the Ukrainian president told Italian TV channel Rai 1.",
        "desc": "<h2><strong>s?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many years.</p><p>India's rivalry with Pakistan, and increasingly with China, means Russia has remained a key partner for Delhi, even after the collapse of the Soviet Union in the 1990s.</p><p>&nbsp;</p><p><strong>ndia's long-standing ties to Russia have come under the spotlight - especially in the defence sector - following the invasion of Ukraine.</strong></p><p>Finance Minister Nirmala Sitharaman said during a visit to the US in April that India would like to be a 'good friend' to Western countries.</p><p>But she added that India didn't want to be weakened, and needed to ensure its security - taken to mean its long-standing reliance on Russian military equipment - would continue.</p><h2><strong>How dependent is India on Russian arms?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many y</p>",
        "category": "Business",
        "url": "Volodymyr-Zelensky-is-ready-to-speak",
        "banner": "banner-1652457446520-531094542.jpeg",
        "thumbnail": "thumbnail-1652457446506-822360584.jpeg",
        "slug": "",
        "createdAtTimestamp": "1652402567931",
        "createdAtDateTime": "13/5/2565 07:42",
        "__v": 0
    },
    {
        "_id": "627e80d5573fe36115400620",
        "title": "Ukraine crisis: Could India cut its defence ties with Russia?",
        "desc": "<h2><strong>s?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many years.</p><p>India's rivalry with Pakistan, and increasingly with China, means Russia has remained a key partner for Delhi, even after the collapse of the Soviet Union in the 1990s.</p><p>&nbsp;</p><p><strong>ndia's long-standing ties to Russia have come under the spotlight - especially in the defence sector - following the invasion of Ukraine.</strong></p><p>Finance Minister Nirmala Sitharaman said during a visit to the US in April that India would like to be a 'good friend' to Western countries.</p><p>But she added that India didn't want to be weakened, and needed to ensure its security - taken to mean its long-standing reliance on Russian military equipment - would continue.</p><h2><strong>How dependent is India on Russian arms?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many y</p>",
        "category": "Business",
        "url": "Ukrain-crisis",
        "banner": "banner-1652457685110-979945148.jpeg",
        "thumbnail": "thumbnail-1652457685093-330207589.jpeg",
        "slug": "",
        "createdAtTimestamp": "1652402567931",
        "createdAtDateTime": "13/5/2565 07:42",
        "__v": 0
    },
    {
        "_id": "627e8109573fe36115400624",
        "title": "Ukraine war: Threat to Finland over Nato, and Russians shoot civilians - round-up",
        "desc": "<h2><strong>s?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many years.</p><p>India's rivalry with Pakistan, and increasingly with China, means Russia has remained a key partner for Delhi, even after the collapse of the Soviet Union in the 1990s.</p><p>&nbsp;</p><p><strong>ndia's long-standing ties to Russia have come under the spotlight - especially in the defence sector - following the invasion of Ukraine.</strong></p><p>Finance Minister Nirmala Sitharaman said during a visit to the US in April that India would like to be a 'good friend' to Western countries.</p><p>But she added that India didn't want to be weakened, and needed to ensure its security - taken to mean its long-standing reliance on Russian military equipment - would continue.</p><h2><strong>How dependent is India on Russian arms?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many y</p>",
        "category": "Business",
        "url": "Threat-to-Finland-over-Nato",
        "banner": "banner-1652457737745-291882378.jpeg",
        "thumbnail": "thumbnail-1652457737729-323963527.jpeg",
        "slug": "",
        "createdAtTimestamp": "1652402567931",
        "createdAtDateTime": "13/5/2565 07:42",
        "__v": 0
    },
    {
        "_id": "627e7f5f573fe36115400601",
        "title": "Sri Lanka crisis: How war heroes became villains",
        "desc": "<h2><strong>s?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many years.</p><p>India's rivalry with Pakistan, and increasingly with China, means Russia has remained a key partner for Delhi, even after the collapse of the Soviet Union in the 1990s.</p><p>&nbsp;</p><p><strong>ndia's long-standing ties to Russia have come under the spotlight - especially in the defence sector - following the invasion of Ukraine.</strong></p><p>Finance Minister Nirmala Sitharaman said during a visit to the US in April that India would like to be a 'good friend' to Western countries.</p><p>But she added that India didn't want to be weakened, and needed to ensure its security - taken to mean its long-standing reliance on Russian military equipment - would continue.</p><h2><strong>How dependent is India on Russian arms?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many y</p>",
        "category": "Interview",
        "url": "Sri-Lanka-crisis",
        "banner": "banner-1652457311713-920593162.jpeg",
        "thumbnail": "thumbnail-1652457311683-276650335.jpeg",
        "slug": "",
        "createdAtTimestamp": "1652402567931",
        "createdAtDateTime": "13/5/2565 07:42",
        "__v": 0,
        "createdBy": {
            "_id": "62771c4ee352657da55dcdfe",
            "username": "tester",
            "__v": 0
        }
    },
    {
        "_id": "627e800d573fe36115400610",
        "title": "Denisova did not provide any evidence to support her claims and the BBC has not been able to verify them.",
        "desc": "<h2><strong>s?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many years.</p><p>India's rivalry with Pakistan, and increasingly with China, means Russia has remained a key partner for Delhi, even after the collapse of the Soviet Union in the 1990s.</p><p>&nbsp;</p><p><strong>ndia's long-standing ties to Russia have come under the spotlight - especially in the defence sector - following the invasion of Ukraine.</strong></p><p>Finance Minister Nirmala Sitharaman said during a visit to the US in April that India would like to be a 'good friend' to Western countries.</p><p>But she added that India didn't want to be weakened, and needed to ensure its security - taken to mean its long-standing reliance on Russian military equipment - would continue.</p><h2><strong>How dependent is India on Russian arms?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many y</p>",
        "category": "Interview",
        "url": "Denisova-did-not-provide-any",
        "banner": "banner-1652457485010-223692916.jpeg",
        "thumbnail": "thumbnail-1652457485000-405880991.jpeg",
        "slug": "",
        "createdAtTimestamp": "1652402567931",
        "createdAtDateTime": "13/5/2565 07:42",
        "__v": 0
    },
    {
        "_id": "627e8136573fe36115400628",
        "title": "Russia and Finland share a 1,300km (810-mile) border. Finland has been non-aligned since World War Two and has always sought not to antagonise its eastern neighbour.",
        "desc": "<h2><strong>s?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many years.</p><p>India's rivalry with Pakistan, and increasingly with China, means Russia has remained a key partner for Delhi, even after the collapse of the Soviet Union in the 1990s.</p><p>&nbsp;</p><p><strong>ndia's long-standing ties to Russia have come under the spotlight - especially in the defence sector - following the invasion of Ukraine.</strong></p><p>Finance Minister Nirmala Sitharaman said during a visit to the US in April that India would like to be a 'good friend' to Western countries.</p><p>But she added that India didn't want to be weakened, and needed to ensure its security - taken to mean its long-standing reliance on Russian military equipment - would continue.</p><h2><strong>How dependent is India on Russian arms?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many y</p>",
        "category": "Interview",
        "url": "land-share-a-130",
        "banner": "banner-1652457782875-501665071.jpeg",
        "thumbnail": "thumbnail-1652457782765-30136235.jpeg",
        "slug": "",
        "createdAtTimestamp": "1652402567931",
        "createdAtDateTime": "13/5/2565 07:42",
        "__v": 0
    },
    {
        "_id": "627e7fe6573fe3611540060c",
        "title": "Volodymyr Zelensky is ready to speak directly with Russian President Vladimir Putin, but 'only without any intermediaries', the Ukrainian president told Italian TV channel Rai 1.",
        "desc": "<h2><strong>s?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many years.</p><p>India's rivalry with Pakistan, and increasingly with China, means Russia has remained a key partner for Delhi, even after the collapse of the Soviet Union in the 1990s.</p><p>&nbsp;</p><p><strong>ndia's long-standing ties to Russia have come under the spotlight - especially in the defence sector - following the invasion of Ukraine.</strong></p><p>Finance Minister Nirmala Sitharaman said during a visit to the US in April that India would like to be a 'good friend' to Western countries.</p><p>But she added that India didn't want to be weakened, and needed to ensure its security - taken to mean its long-standing reliance on Russian military equipment - would continue.</p><h2><strong>How dependent is India on Russian arms?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many y</p>",
        "category": "Business",
        "url": "Volodymyr-Zelensky-is-ready-to-speak",
        "banner": "banner-1652457446520-531094542.jpeg",
        "thumbnail": "thumbnail-1652457446506-822360584.jpeg",
        "slug": "",
        "createdAtTimestamp": "1652402567931",
        "createdAtDateTime": "13/5/2565 07:42",
        "__v": 0
    },
    {
        "_id": "627e80d5573fe36115400620",
        "title": "Ukraine crisis: Could India cut its defence ties with Russia?",
        "desc": "<h2><strong>s?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many years.</p><p>India's rivalry with Pakistan, and increasingly with China, means Russia has remained a key partner for Delhi, even after the collapse of the Soviet Union in the 1990s.</p><p>&nbsp;</p><p><strong>ndia's long-standing ties to Russia have come under the spotlight - especially in the defence sector - following the invasion of Ukraine.</strong></p><p>Finance Minister Nirmala Sitharaman said during a visit to the US in April that India would like to be a 'good friend' to Western countries.</p><p>But she added that India didn't want to be weakened, and needed to ensure its security - taken to mean its long-standing reliance on Russian military equipment - would continue.</p><h2><strong>How dependent is India on Russian arms?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many y</p>",
        "category": "Business",
        "url": "Ukrain-crisis",
        "banner": "banner-1652457685110-979945148.jpeg",
        "thumbnail": "thumbnail-1652457685093-330207589.jpeg",
        "slug": "",
        "createdAtTimestamp": "1652402567931",
        "createdAtDateTime": "13/5/2565 07:42",
        "__v": 0
    },
    {
        "_id": "627e8109573fe36115400624",
        "title": "Ukraine war: Threat to Finland over Nato, and Russians shoot civilians - round-up",
        "desc": "<h2><strong>s?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many years.</p><p>India's rivalry with Pakistan, and increasingly with China, means Russia has remained a key partner for Delhi, even after the collapse of the Soviet Union in the 1990s.</p><p>&nbsp;</p><p><strong>ndia's long-standing ties to Russia have come under the spotlight - especially in the defence sector - following the invasion of Ukraine.</strong></p><p>Finance Minister Nirmala Sitharaman said during a visit to the US in April that India would like to be a 'good friend' to Western countries.</p><p>But she added that India didn't want to be weakened, and needed to ensure its security - taken to mean its long-standing reliance on Russian military equipment - would continue.</p><h2><strong>How dependent is India on Russian arms?</strong></h2><p>India is one of the world's largest buyers of weapons, and had a close defence relationship with the former Soviet Union for many y</p>",
        "category": "Business",
        "url": "Threat-to-Finland-over-Nato",
        "banner": "banner-1652457737745-291882378.jpeg",
        "thumbnail": "thumbnail-1652457737729-323963527.jpeg",
        "slug": "",
        "createdAtTimestamp": "1652402567931",
        "createdAtDateTime": "13/5/2565 07:42",
        "__v": 0
    },
]
